# Generated by Django 4.0.5 on 2022-06-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_filme_categoria_filme_data_criacao_filme_descrica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='filme.filme')),
            ],
        ),
    ]
