# Generated by Django 4.0.5 on 2022-06-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_episodios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episodios',
            new_name='Episodio',
        ),
    ]
